// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvCFBgAiok4AiVNTGpgPi6wL0csRCyl7Q',
    appId: '1:320596142744:web:75400a0f4f1e0504d13eed',
    messagingSenderId: '320596142744',
    projectId: 'chat-b254f',
    authDomain: 'chat-b254f.firebaseapp.com',
    databaseURL: 'https://chat-b254f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-b254f.firebasestorage.app',
    measurementId: 'G-EW3LC3BX9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf2V1otWewIuhVSzfHYRHZSZIfkpDWabw',
    appId: '1:320596142744:android:d10ff030f7a63aacd13eed',
    messagingSenderId: '320596142744',
    projectId: 'chat-b254f',
    databaseURL: 'https://chat-b254f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-b254f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqlvCXQJN67cem5oxMjd3CZOS8UJraFLc',
    appId: '1:320596142744:ios:0cdf351aceb00ba4d13eed',
    messagingSenderId: '320596142744',
    projectId: 'chat-b254f',
    databaseURL: 'https://chat-b254f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-b254f.firebasestorage.app',
    iosBundleId: 'com.example.communityapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqlvCXQJN67cem5oxMjd3CZOS8UJraFLc',
    appId: '1:320596142744:ios:0cdf351aceb00ba4d13eed',
    messagingSenderId: '320596142744',
    projectId: 'chat-b254f',
    databaseURL: 'https://chat-b254f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-b254f.firebasestorage.app',
    iosBundleId: 'com.example.communityapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvCFBgAiok4AiVNTGpgPi6wL0csRCyl7Q',
    appId: '1:320596142744:web:e83e106241660aa2d13eed',
    messagingSenderId: '320596142744',
    projectId: 'chat-b254f',
    authDomain: 'chat-b254f.firebaseapp.com',
    databaseURL: 'https://chat-b254f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-b254f.firebasestorage.app',
    measurementId: 'G-XMN71HRCDE',
  );
}
